version: "3"

volumes:
  datafiles:

networks:
  crosswordapi-net:
    driver: bridge

services:
  db:
    container_name: crosswordapi.db
    image: mysql:8.0.15
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_TCP_PORT: 3360
    networks:
      - crosswordapi-net

  scraper:
    container_name: crosswordapi.scraper
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      - DBHOST=db
      - DBPORT=3360
      - DBUSER=root
      - DBPASSWORD=secret
      - DATABASE=dictionary
      - CHROMEDRIVER_WHITELISTED_IPS=
      - CHROMEDRIVER_PORT=4444
    ports:
      - 4444:4444
    cap_add:
      - "SYS_ADMIN"
    networks:
      - crosswordapi-net

    # see https://github.com/SeleniumHQ/docker-selenium/issues/79
    # volumes:
    #   - /dev/shm:/dev/shm

