version: '3'

volumes:
  datafiles:

networks:
  crosswordapi-net:
    driver: bridge

services:
  db:
    container_name: crosswordapi.db
    image: mysql:8.0.15
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_TCP_PORT: 3360
    networks:
      - crosswordapi-net

  api:
    container_name: crosswordapi.api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      - DBHOST=db
      - DBPORT=3360
      - DBPASSWORD=secret
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - crosswordapi-net      

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
    restart: always
    environment:
      #DOMAINS: 'alpacatracker.com -> http://api:5000'
      #STAGE: 'production'    
      DOMAINS: 'example.com -> http://api:5000'
      STAGE: local # self signed certificate, note modify your hosts file to have example.com resolving to your docker host 
      # c:\Windows\System32\Drivers\etc\hosts => 127.0.0.1           example.com 
      # FORCE_RENEW: 'true'
    networks:
      - crosswordapi-net
  