// <auto-generated />
using System;
using CrossWord.Scraper.MySQLDbService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrossWord.Scraper.Migrations
{
    [DbContext(typeof(SynonymDbContext))]
    [Migration("20190309140759_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("CrossWord.Scraper.MySQLDbService.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Language");

                    b.Property<int>("NumberOfLetters");

                    b.Property<int>("NumberOfWords");

                    b.Property<int?>("ParentWordId");

                    b.Property<long>("UserId");

                    b.Property<string>("Value");

                    b.HasKey("WordId");

                    b.HasIndex("ParentWordId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("CrossWord.Scraper.MySQLDbService.Models.Word", b =>
                {
                    b.HasOne("CrossWord.Scraper.MySQLDbService.Models.Word", "Parent")
                        .WithMany("Synonyms")
                        .HasForeignKey("ParentWordId");
                });
#pragma warning restore 612, 618
        }
    }
}
